version: '3'

services:
  db-postgres:
    image: postgres
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  db-mongo:
    image: mongo
    container_name: db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
